### ISSUE TITLE
incorrect import.

### ISSUE THREAD

**Issue by FlameKat53** [omijh/PicoFusee#2]
OLD: `const fusee_payload`
NEW: `const data`

code in the index.js file:
LINE 2: `import fusee_payload from "./compressed";`

notice the error there?

**Comment by FlameKat53** [comment]
that's with the dragonbox import

**Comment by omijh** [comment]
Yes i saw it thanks ill update the code

**Comment by FlameKat53** [comment]
awesome, thanks :)

**Comment by FlameKat53** [comment]
Sadly it doesn't work. when i run .load i get "null" no matter what i do

**Comment by FlameKat53** [comment]
are there any payloads that work? i don't care what it is, i'd like my switch to do something with your app, then i'll be good :)

**Comment by omijh** [comment]
Yeah i get null it''s because pico has very limited ram 200 kb and because it's js i can't just send the binary file

**Comment by omijh** [comment]
https://github.com/kaluma-project/kaluma/discussions/498#discussioncomment-2248971

**Comment by FlameKat53** [comment]
can i not read from the ROM? (2MB Flash)

**Comment by omijh** [comment]
well i could save the 64 kb dragonboot on the flash but i am still unable to stream it from the bin file. instead i have to convert the bin to uint8 array that increases it's size by a lot :( 
i had to use js because thats the only programing language that's not embedded on pico 
there are samd implementation in arduino but usb host library in arduino is not yet supported for pico

**Comment by FlameKat53** [comment]
yeah, i understand, been at this all night haha. i think micropython is not embedded is it? i know i can just save my files to it

**Comment by FlameKat53** [comment]
i have arduino rp2040 connect, it has a large flash memory size

**Comment by omijh** [comment]
next ill try to implement [rust](https://github.com/austinhartzheim/fusee-gelee) implementation on pico but i don't have much hope since the rust implementation on pico is embedded version of rust

**Comment by FlameKat53** [comment]
i believe in you.

**Comment by omijh** [comment]
> i have arduino rp2040 connect, it has a large flash memory size

but it's not the disk space that we are limited by when using this js implementation it's the available ram 
there is tiny 2040 with 8mb disk space but that too has the same amount of ram since ram is built-in rp2040 microcontroller

**Comment by FlameKat53** [comment]
oh, my fault :/

**Comment by FlameKat53** [comment]
so ram is limited. how can we stream a file, or have a lfs filesystem? https://kalumajs.org/docs/api/file-system/

**Comment by omijh** [comment]
```
fs.read(fd, buffer[, offset[, length[, position]]]) [#](https://kalumajs.org/docs/api/file-system/#fs-read)
let buffer = new Uint8Array(10);
// read 10 bytes from the start 
```
we can read that way creating small buffers, the problem is i am not sure how we can send the payload bit by bit in js to the switch also testing it is a pain since i don't have a separate debug prob for pico

**Comment by FlameKat53** [comment]
sigh :/

**Comment by omijh** [comment]
it's also possible to use this project if we find a really really tiny payload since loading intermezzo in memory has no problems what so ever

**Comment by omijh** [comment]
you can replicate the error with just two lines 

```
import fusee_payload from "./compressed";
console.log(fusee_payload)
```

**Comment by FlameKat53** [comment]
how much ram does js use?

**Comment by omijh** [comment]
js itself doesn't use much but when we extract the bin file, by itself its around ~300kb just the payload you can see it when you bundle with and without the payload.js

**Comment by omijh** [comment]
the payload file bin itself is 64 kb which is tiny but when extracted to hexadecimal it becomes much larger in size.
by cutting the payload i found if you delete the payload bits about 2/3 of them from the array, it no longer returns null

**Comment by FlameKat53** [comment]
does that mean it works?

**Comment by omijh** [comment]
yeah if it no longer returns null i can debug it further, but that's not the entire payload so it's corrupted so it won't work

**Comment by FlameKat53** [comment]
oh.
